### ISSUE TITLE
Gcloud: command not found / decompress_destroy / upgrade_destroy

### ISSUE THREAD

**Issue by jeremyrcampb** [terraform-google-modules/terraform-google-project-factory#376] opened 2020-02-12 13:50 UTC
project-factory has never been happy for me even after subsequent applies, it always wanted to re-create two resources.

When on 6.2.0, I just let it delete and recreate each apply.  

When I moved to 7.0, it stopped deleting the resources successfully.

When I added config:

```default_service_account = "keep"```

Now it only wants to delete those resources, not re-create them.  But since the delete fails, I'm stuck.

These are the resources in question:

 ``` 
# module.project-factory.module.project-factory.module.gcloud_disable.null_resource.decompress_destroy[0] will be destroyed
  - resource "null_resource" "decompress_destroy" {
      - id = "1312074385415559420" -> null
    }

  # module.project-factory.module.project-factory.module.gcloud_disable.null_resource.upgrade_destroy[0] will be destroyed
  - resource "null_resource" "upgrade_destroy" {
      - id = "8860384152163875421" -> null
    } 
```

Config:
```
module "project-factory" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 7.0"

  name                = local.project_name
  random_project_id   = "true"
  org_id              = var.org_id
  folder_id           = var.folder_id
  billing_account     = var.billing_account_id
  activate_apis       = var.gcp_apis
  default_service_account = "keep"
  labels              = {"redacted": "redacted"}
} 
```

But deletion of these two resources fail, unable to use google-cloud-sdk.tar.gz.

```
Error: Error running command 'tar -xzf .terraform/modules/project-factory.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/2de0224a/google-cloud-sdk.tar.gz -C .terraform/modules/project-factory.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/2de0224a && cp .terraform/modules/project-factory.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/2de0224a/jq .terraform/modules/project-factory.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/2de0224a/google-cloud-sdk/bin/': exit status 1. Output: tar: Error opening archive: Failed to open '.terraform/modules/project-factory.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-84e31b8/cache/2de0224a/google-cloud-sdk.tar.gz'
```

Environment: 
```
% terraform -v
Terraform v0.12.20
+ provider.google v2.20.1
+ provider.google-beta v3.5.0
+ provider.null v2.1.2
+ provider.random v2.2.1

% gcloud -v
Google Cloud SDK 275.0.0
alpha 2019.05.17
beta 2019.05.17
bq 2.0.51
core 2020.01.03
gsutil 4.46
kubectl 2019.11.04
```

**Comment by morgante** [comment] 2020-02-20 14:41
What's the environment you're attempting to run from?

**Comment by jeremyrcampb** [comment] 2020-02-20 17:34
I started on Terraform Cloud, but when I encountered these issues I brought state local and also reproduced on my desktop.

**Comment by kuwas** [comment] 2020-02-20 17:34
Seems to be related to: https://github.com/terraform-google-modules/terraform-google-gcloud/issues/27

**Comment by skinlayers** [comment] 2020-02-20 23:38
I'm encountering the same issue when running locally.

```
data "google_organization" "org" {
  domain = "example.com"
}

data "google_billing_account" "default" {
  display_name = "Example Billing Account"
  open         = true
}

module "project-factory" {
  source  = "terraform-google-modules/project-factory/google//modules/gsuite_enabled"
  version = "~> 7.0.0"

  billing_account    = data.google_billing_account.default.id
  name               = data.google_client_config.default.project
  org_id             = data.google_organization.org.id
  shared_vpc_enabled = false
  create_group       = true

  folder_id = "0000000000000000"

  disable_dependent_services  = false
  disable_services_on_destroy = false

  activate_apis = [
    "compute.googleapis.com",
    // Required by BKPR prometheus-to-sd-exporter
    "logging.googleapis.com",
  ]
}

resource "gsuite_group_member" "editors" {
  group = module.project-factory.group_email
  email = "me@example.com"
  role = "OWNER"
}

// Required for ssh access from bastion to gke nodes
// See https://cloud.google.com/compute/docs/instances/managing-instance-access#limitations
resource "google_compute_project_metadata_item" "ssh_keys" {
  key     = "ssh-keys"
  project = module.project-factory.project_id
  value   = <<-EOT
    me:ssh-ed25519 AAAAC3NzXXXXXXX me@example.com
  EOT
}

module "tfe_service_account" {
  source     = "terraform-google-modules/service-accounts/google"
  version    = "~> 2.0.2"
  project_id = module.project-factory.project_id
  names      = ["terraform-enterprise"]
  #generate_keys = true
  project_roles = [
    "${module.project-factory.project_id}=>roles/owner",
  ]
}
```

**Comment by morgante** [comment] 2020-02-21 00:21
Thanks for the confirmation.

I'm going to spend some time playing around with Terraform Cloud to try to replicate and hopefully have a fix early next week.

**Comment by mhamrah** [comment] 2020-02-23 13:12
I believe the problem is that `gcloud` isn't installed in the terraform cloud environment, and I don't believe there is a way to do so.

**Comment by kuwas** [comment] 2020-02-24 01:57
@morgante Like I mentioned in https://github.com/terraform-google-modules/terraform-google-gcloud/issues/27, this module just needs to be built for and tested with ephemeral build environments as the primary consumer.

You can actually reproduce this issue locally by simulating the behavior, see below.

```
terraform init
terraform apply -auto-approve
rm -rf .terraform
terraform init
terraform destroy -auto-approve # error will show up here
```

```
module "project-factory" {
  version                 = "~> 7.0"
  source                  = "terraform-google-modules/project-factory/google"
  org_id                  = "<redacted>"
  folder_id               = "<redacted>"
  billing_account         = "<redacted>"
  project_id              = "test-project-123asdf"
  name                    = "test-project"
  default_service_account = "disable"
}
```

**Comment by dooman87** [comment] 2020-03-23 19:50
We had similar issue while using `default_service_account = "delete"`. We are running terraform on GCP Cloud Build. That might be easier for you to replicate @morgante? 

The easy workaround that worked for us was to set `skip_gcloud_download = true` in the module call. However you would need to have `gcloud` in your docker image.

**Comment by thesuperzapper** [comment] 2020-04-06 23:42
I believe this is related to #391 and #396

**Comment by pryankster** [comment] 2020-04-08 15:46
I have this issue.  Trying to apply some output changes (no changes to resources), but terraform thinks that it needs to update/destroy gcloud?

```
Error: Error running command 'tar -xzf .terraform/modules/project.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/b8c89790/google-cloud-sdk.tar.gz -C .terraform/modules/project.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/b8c89790 && cp .terraform/modules/project.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/b8c89790/jq .terraform/modules/project.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/b8c89790/google-cloud-sdk/bin/': exit status 2. Output: tar (child): .terraform/modules/project.project-factory.gcloud_disable/terraform-google-modules-terraform-google-gcloud-09a6f10/cache/b8c89790/google-cloud-sdk.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
How can I get myself out of this without destroying all of my resources?

There's no terraform-google-modules-terraform-google-cloud-09a6f10 directory ...
```sh
# ls .terraform/modules/project.project-factory.gcloud_disable/
terraform-google-gcloud-0.5.1/
```
So it looks like the cache directory is wrong?

**Comment by slimm609** [comment] 2020-04-08 16:37
https://github.com/terraform-google-modules/terraform-google-gcloud/issues/38

This looks very similar to the issue I am still having with the cache directory.

**Comment by thesuperzapper** [comment] 2020-04-09 02:04
@pryankster you have to use `terraform state rm project.project-factory.gcloud_disable` (which is fine to do as its just a null_operator.

But read the docs first: https://www.terraform.io/docs/commands/state/rm.html

**Comment by pryankster** [comment] 2020-04-09 14:34
@thesuperzapper Thanks, that's what I ended up doing ... was a bit scary the first time :-) as we are still all getting our feet with with TF & GCP

**Comment by rosmo** [comment] 2020-08-18 11:58
It would be very nice to update the included gcloud module to the latest, since there's a fix for this: https://github.com/terraform-google-modules/terraform-google-gcloud/issues/27

Currently runs in an ephemeral container-based CI/CD system like Gitlab are breaking.

**Comment by bharathkkb** [comment] 2020-12-19 02:30
Should not be relevant as gcloud module has been replaced by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/491

**Closed by bharathkkb** 2020-12-19 02:30 UTC
