### ISSUE TITLE
The provider provider.google-beta does not support resource type "google_project_service_identity"

### ISSUE THREAD

**Issue by amadhus** [terraform-google-modules/terraform-google-project-factory#481] opened 2020-10-21 19:54 UTC
Hi Team,

Actually, I was trying to test the terraform & terragrunt execution with its latest versions for my existing Google Cloud Foundation code. 

Currently I am testing with Terraform = 0.13.4 version and project-factory module = 9.2.0.

Please let me know if you have any questions or need more information?

Thanks,
Madhu

**Comment by bharathkkb** [comment] 2020-10-21 20:50
Hi @amadhus 
Please update to a provider version > 3.38
x-ref: https://github.com/terraform-google-modules/terraform-google-project-factory/issues/462

**Comment by amadhus** [comment] 2020-10-22 18:12
@bharathkkb After updating the version I am getting a different error now..

**Comment by amadhus** [comment] 2020-10-22 18:15
```
on .terraform.modules/gcp_name_utils/main.tf line 18, in terraform:
18: required_version = "~>0.12.0"
```

@bharathkkb but the confusing part for me is that */modules/gcp_name_utils folder doesn't even exist on the project-project factory module itself.

Please correct me if I am wrong and if I am missing something here.

Thanks,
Madhu

**Comment by amadhus** [comment] 2020-10-22 19:03
@bharathkkb looks like it is a different module i.e., terraform-google-utils

**Comment by bharathkkb** [comment] 2020-12-19 02:38
Hi @amadhus 
Apologies as I missed your previous comment. If this is still a problem please open an issue on `terraform-google-utils`. `terraform-google-utils` is not used within project factory. Closing out this issue as your root cause has been fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/513 where we added `required_providers`

**Closed by bharathkkb** 2020-12-19 02:38 UTC
