### ISSUE TITLE
Error when shared_vpc is not empty but shared_vpc_subnets is

### ISSUE THREAD

**Issue by jcejohnson** [terraform-google-modules/terraform-google-project-factory#229] opened 2019-06-18 22:41 UTC
Usecase:

```
module "myProject" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 2.4.0"

  name = "myProject"

  billing_account    = "${var.billing_id}"
  credentials_path   = "${var.credentials_path}"
  folder_id          = "${var.folder_id}"
  org_id             = "${var.org_id}"
  random_project_id  = "true"
  shared_vpc         = "${var.shared_vpc}"
  shared_vpc_subnets = [""] # Or [] or omit entirely.

  labels = {}

  activate_apis = [
    "compute.googleapis.com",
    "servicenetworking.googleapis.com",
  ]
}
```

Errors during terraform plan:

```
$ terraform plan

Error: module.myProject.module.project-factory.google_compute_subnetwork_iam_member.apis_service_account_role_to_vpc_subnets: 1 error(s) occurred:

* module.myProject.module.project-factory.google_compute_subnetwork_iam_member.apis_service_account_role_to_vpc_subnets: At column 44, line 1: list "var.shared_vpc_subnets" does not have any elements so cannot determine type. in:

${element(split("/", var.shared_vpc_subnets[count.index]),(index(split("/", var.shared_vpc_subnets[count.index]),"subnetworks"))+1)}



Error: module.myProject.module.project-factory.google_compute_subnetwork_iam_member.gke_shared_vpc_subnets: 1 error(s) occurred:

* module.myProject.module.project-factory.google_compute_subnetwork_iam_member.gke_shared_vpc_subnets: At column 44, line 1: list "var.shared_vpc_subnets" does not have any elements so cannot determine type. in:

${element(split("/", var.shared_vpc_subnets[count.index]),(index(split("/", var.shared_vpc_subnets[count.index]),"subnetworks"))+1)}



Error: module.myProject.module.project-factory.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: 1 error(s) occurred:

* module.myProject.module.project-factory.google_compute_subnetwork_iam_member.group_role_to_vpc_subnets: At column 44, line 1: list "var.shared_vpc_subnets" does not have any elements so cannot determine type. in:

${element(split("/", var.shared_vpc_subnets[count.index]), (index(split("/", var.shared_vpc_subnets[count.index]),"regions"))+1)}



Error: module.myProject.module.project-factory.google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets: 1 error(s) occurred:

* module.myProject.module.project-factory.google_compute_subnetwork_iam_member.service_account_role_to_vpc_subnets: At column 44, line 1: list "var.shared_vpc_subnets" does not have any elements so cannot determine type. in:

${element(split("/", var.shared_vpc_subnets[count.index]),(index(split("/", var.shared_vpc_subnets[count.index]),"subnetworks"))+1)}
```

**Comment by aaron-lane** [comment] 2019-06-21 15:43
@jcejohnson I apologize for the frustrating experience.

Just to confirm, this error occurs even if you include an empty string element?

**Comment by jcejohnson** [comment] 2019-06-21 15:50
Aye. We tried with nothing (i.e. - take the default), empty list and list with empty string. All give the error.
The silver lining is that it made us re-examine our usecase and found that we actually *should* be passing a non-empty list.

**Comment by bohdanyurov-gl** [comment] 2019-06-26 10:17
@jcejohnson I've tried creating project using your example config, it worked for me.

Could you please give more details? Can you retry it with tf0.12 version (aaron-lane-0.12)?

**Comment by jcejohnson** [comment] 2019-06-26 14:27
Interesting. We're using 0.11.13, we haven't taken the plunge into 0.12.x yet.

**Comment by bohdanyurov-gl** [comment] 2019-06-26 15:52
ok, I've rechecked it with TF 0.11:
![image](https://user-images.githubusercontent.com/47155283/60195258-71252000-9843-11e9-96da-97233643f6b0.png)
![image](https://user-images.githubusercontent.com/47155283/60195298-81d59600-9843-11e9-8f3e-c71d420c63ca.png)

**Comment by morgante** [comment] 2019-06-26 15:58
Since we're unable to reproduce this and @jcejohnson has changed to using an explicit subnet list, I'm going to close this out for now.

If anyone else encounters it, please comment and we can reopen.

**Closed by morgante** 2019-06-26 15:58 UTC
Labels: bug
