### ISSUE TITLE
Preconditions fail on windows due to wrongly parsed argument

### ISSUE THREAD

**Issue by cedriclevarlet** [terraform-google-modules/terraform-google-project-factory#356] opened 2020-01-09 12:05 UTC
**Operating system:** Windows 10
**Terminal:** command prompt and powershell
**Version:** >=6.2.0

**Issue:**
The precondition_command encapsulates the provided arguments by double quotes. This seems to be incorrectly processed by precondition.py's argparse as the argument_type under BillingAccount method receives a string including the double quotes which then fails as it does not match the regex rules.

Attempting to apply the plan results in this error:
'"XXXXXX-XXXXXX-XXXXXX"' is not a valid billing account ID format

In locals.py; changing 

`preconditions_command = "${var.python_interpreter_path} ${local.preconditions_py_absolute_path} %{for key, value in local.attributes}--${key}=\"${value}\" %{endfor}"`

to 

`preconditions_command = "${var.python_interpreter_path} ${local.preconditions_py_absolute_path} %{for key, value in local.attributes}--${key}=${value} %{endfor}"`

works however, this is not a good solution as it could introduces further problems with other arguments.

**Comment by taylorludwig** [comment] 2020-01-09 18:54
Does it still work in linux if we remove the quotes?  If the quotes make it through to the python argparse in windows but not linux, we could update the python script to work wither either format.

**Comment by cedriclv** [comment] 2020-01-11 15:21
Sorry for not answering earlier; I was trying to understand a bit more what was happening behind the scene.

Running the precondition.py file directly and passing the values as intended does not produce the error. As such I wanted to isolate the issue as much as possible and found it to be tied to the local-exec provisioner. 

test.py
```python
import argparse


def validate(string):
    print(string)
    print("value")
    return str(string)


parser = argparse.ArgumentParser(description='Process value.')
parser.add_argument('--test', type=validate,
                    help='sum the integers (default: find the max)')

args = parser.parse_args()
```

main.tf
```terraform
resource null_resource "blah" {
  provisioner "local-exec" {
    command = "python ./test.py --test=\"value\""
  }
}
```

terraform apply:
```cmd
null_resource.blah: Creating...
null_resource.blah: Provisioning with 'local-exec'...
null_resource.blah (local-exec): Executing: ["cmd" "/C" "python ./test.py --test=\"value\""]
null_resource.blah (local-exec): "value"
null_resource.blah (local-exec): value
null_resource.blah: Creation complete after 1s [id=2085324832574525216]
```

This should therefore be fixed upstream. Until then, if windows 10 support is required; it could potentially be resolved directly within the python script by striping the quotes before doing the validation check.

```python
    def argument_type(cls,
                      string,
                      pat=re.compile(r"[A-Z0-9]{6}-[A-Z0-9]{6}-[A-Z0-9]{6}")):
        string = string.strip('"') #  windows fix
        if not pat.match(string):
            msg = "%r is not a valid billing account ID format" % string
            raise argparse.ArgumentTypeError(msg)
        return string
```

Whilst this is not great it would avoid potential issues that could arise by modifying the initial command.

**Comment by morgante** [comment] 2020-01-13 01:06
Thanks for investigating this! I agree that the best fix (for now) would be to simply strip the quotes automatically within Python and I'd be happy to accept a PR adding that.

**Comment by bharathkkb** [comment] 2020-12-19 02:34
fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/478

**Closed by bharathkkb** 2020-12-19 02:34 UTC
Labels: P3, bug, triaged
