### ISSUE TITLE
Using count with TF 0.13 seems fraught with problems

### ISSUE THREAD

**Issue by haf** [terraform-google-modules/terraform-google-project-factory#487] opened 2020-10-29 08:50 UTC
This module crashes when used with TF 0.13 in these cases:

Example when using the budget feature:

```
Error: Invalid count argument

  on .terraform/modules/host-project/modules/core_project_factory/main.tf line 349, in resource "google_project_usage_export_bucket" "usage_report_export":
 349:   count = var.usage_bucket_name != "" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

Using a local, so that

```diff
-   usage_bucket_name           = google_storage_bucket.usage_report.name
+   usage_bucket_name           = local.usage_report_bucket
```

makes it pass. Despite this later on in the project factory declaration:

```
  depends_on = [google_storage_bucket.usage_report]
```

Moving on, by using the local instead (having to manually declare `depends_on` as a result of that workaround): later, when using the GSuite integration:

```
Error: Invalid count argument

  on .terraform/modules/host-project.project-factory.gcloud_disable/main.tf line 57, in resource "random_id" "cache":
  57:   count = (! local.skip_download) ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

This crash seems worse since the only knob I have is a boolean, and that is already "known" statically, so the problem lies inside this module in how it composes its child modules.

Hashicorp has [a summary of the count problem](https://github.com/hashicorp/terraform/issues/26078#issuecomment-710060287):

> The use of depends_on is only for ordering in rare circumstances where Terraform is unable to determine dependency orders. For count and for_each, Terraform requires that the arguments are known at time of plan, and you can't use depends_on to delay this until mid-apply.

> With how Terraform works at present, we consider this sort of configuration to be incorrect. Using resource computed outputs as arguments to count and for_each is not recommended. Instead, using variables or derived local values which are known at plan time is the preferred approach. If you choose to go ahead with using computed values for count/for_each, this will sometimes require you to work around this using -target as illustrated above.

**Comment by morgante** [comment] 2020-10-29 15:23
I'm not sure what you're asking for here.

The limitations of `count` and `for_each` are well understood (and based on Terraform core, not this module).

The solution is that you should not use dynamic values as inputs.

**Comment by haf** [comment] 2020-10-29 15:33
I'm not, I'm using `false`, like I wrote above.

**Comment by morgante** [comment] 2020-10-29 15:36
Ok, then where is an error being raised? Please share your full Terraform config.

**Comment by haf** [comment] 2020-10-29 15:39
```
locals {
  usage_report_bucket = "example-usage-report"
}

/******************************************
  Provider configuration
 *****************************************/
provider "google" {
  version     = "~> 3.30"
  credentials = file(var.credentials_path)
}

provider "google-beta" {
  version     = "~> 3.30"
  credentials = file(var.credentials_path)
}

provider "null" {
  version = "~> 2.1"
}

provider "random" {
  version = "~> 2.2"
}


/******************************************
  Folders Creation
  https://github.com/terraform-google-modules/terraform-google-project-factory/blob/79f7c953a5267b0d22c2e9396136e27319320ae0/examples/project-hierarchy/main.tf#L54
 *****************************************/

resource "google_folder" "shared" {
  display_name = "Shared"
  parent       = "organizations/${var.organization_id}"
}

resource "google_folder" "labs" {
  display_name = "Labs"
  parent       = "organizations/${var.organization_id}"
}

resource "google_folder" "prod" {
  display_name = "Prod"
  parent       = "organizations/${var.organization_id}"
}


resource "google_storage_bucket" "usage_report" {
  name     = local.usage_report_bucket
  location = "EU"
  project  = var.host_project_name
}

# An additional budget with more options
resource "google_pubsub_topic" "usage_report_alerts" {
  name    = "usage_report_alerts"
  project = var.host_project_name
}
module "host-project" {
  source = "terraform-google-modules/project-factory/google"
  # source  = "terraform-google-modules/project-factory/google//modules/gsuite_enabled"
  version = "~> 9.2"

  activate_apis = [
    "compute.googleapis.com",
    "billingbudgets.googleapis.com"
  ]

  billing_account                = var.billing_account
  bucket_location                = "EU"
  bucket_project                 = "example-seed"
  bucket_name                    = "example-tf-state"
  bucket_versioning              = true
  credentials_path               = var.credentials_path
  default_service_account        = "disable"
  domain                         = "example.com"
  enable_shared_vpc_host_project = true
  folder_id                      = google_folder.shared.id
  lien                           = true
  name                           = var.host_project_name
  org_id                         = var.organization_id
  skip_gcloud_download           = true

  # Budget
  budget_alert_pubsub_topic   = google_pubsub_topic.usage_report_alerts.name
  budget_alert_spent_percents = [0.5, 0.7, 1]
  budget_amount               = 400
  usage_bucket_name           = local.usage_report_bucket

  # GSuite
  # https://github.com/terraform-google-modules/terraform-google-project-factory/issues/484
  # sa_group                       = "gsuite-service-accounts@example.com"
  # create_group                   = true

  depends_on = [google_storage_bucket.usage_report]
}

resource "google_project_iam_member" "project" {
  project = module.host-project.project_id
  role    = "roles/editor"
  member  = "user:example@example.com"
}

```

**Comment by morgante** [comment] 2020-10-29 16:05
What error do you get with this config?

**Comment by haf** [comment] 2020-10-29 16:07
```

Error: Invalid count argument

  on .terraform/modules/host-project.project-factory.gcloud_disable/main.tf line 57, in resource "random_id" "cache":
  57:   count = (! local.skip_download) ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

```

**Comment by morgante** [comment] 2020-10-29 16:10
@haf Could you try leaving the skip_download off entirely?

**Comment by EppO** [comment] 2020-11-03 19:55
I ran into the same issue:
```terraform
Error: Invalid count argument

  on .terraform/modules/azurevm/vm_extensions.tf line 93, in resource "azurerm_virtual_machine_extension" "linux_virtual_machine_extension_diagnostics":
  93:   count                      = local.vm_settings["linux_diagnostics"] == true && var.sa_diagnostics != "" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
`local.vm_settings` is a a map computed after merging another map of default values with a user input variable, `local.vm_settings["linux_diagnostics"]` specifically is a boolean value and `var.sa_diagnostics` is a user input variable (string value). So at plan, everything should be determined. 

Using 
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.34.0
```

**Comment by morgante** [comment] 2020-11-03 19:58
@EppO This is not the right repo to report issues around Terraform core or the Azure provider.

This is the Google provider for Terraform. You want terraform core: https://github.com/hashicorp/terraform

**Comment by EppO** [comment] 2020-11-03 20:00
oh I'm sorry, I ended up here after a google search of the very same issue. I'll open the issue on the terraform repo. Thanks

**Comment by haf** [comment] 2020-11-04 06:22
Awesome, it's solved! @morgante How did you solve it?

**Comment by morgante** [comment] 2020-11-04 07:25
@haf Just to confirm, you're no longer seeing this issue?

> Works, but is not the solution. It's a bool, it should be possible to set.

Agreed, just trying to diagnose the cause since I can't reproduce.

**Comment by haf** [comment] 2020-11-04 15:23
Yes, I think I've worked around it by not using that setting. But have you tried latest Terraform and setting the settings I used? I repro it every time.

**Comment by bharathkkb** [comment] 2020-12-19 02:27
This should now be fixed by https://github.com/terraform-google-modules/terraform-google-project-factory/pull/491

**Closed by bharathkkb** 2020-12-19 02:27 UTC
