### ISSUE TITLE
Can we please provide an actual API instead of shell scripts?

### ISSUE THREAD

**Issue by arybka777** [terraform-google-modules/terraform-google-project-factory#439] opened 2020-08-12 14:11 UTC
Can we please provide an actual API instead of shell scripts?

Here is an example:
https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/core_project_factory/scripts/modify-service-account.sh

Thank you

**Comment by morgante** [comment] 2020-08-12 15:04
Dupe of #408.

**Closed by morgante** 2020-08-12 15:04 UTC
